title: embedded-diver
description: some notes while analyzing embedded projects
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
url: embedded-diver.github.io

sidebar:
  - label: Home 
    children:
      - home_page

search_enable: true

    